namespace AutoTextBox_Popup
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.button1 = new System.Windows.Forms.Button();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(237, 166);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(69, 22);
            this.label1.TabIndex = 0;
            this.label1.Text = "&State:-";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(249, 215);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(57, 22);
            this.label2.TabIndex = 1;
            this.label2.Text = "&City:-";
            // 
            // textBox1
            // 
            this.textBox1.AutoCompleteCustomSource.AddRange(new string[] {
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "The Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "C",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo, Democratic Republic of the",
            "Congo, Republic of the",
            "Costa Rica",
            "Côte d’Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor (Timor-Leste)",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gaon",
            "The Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea, North",
            "Korea, South",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia, Federated States of",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar (Burma)",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Sant Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Sudan, South",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"});
            this.textBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.textBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.textBox1.Location = new System.Drawing.Point(321, 115);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(170, 31);
            this.textBox1.TabIndex = 2;
            // 
            // textBox2
            // 
            this.textBox2.AutoCompleteCustomSource.AddRange(new string[] {
            "Andhra Pradesh",
            "Arunachal Pradesh",
            "Assam",
            "Bihar",
            "Chhattisgarh",
            "Goa",
            "Gujarat",
            "Haryana",
            "Himachal Pradesh",
            "Jharkhand",
            "Karnataka",
            "Keral",
            "Madhya Pradesh",
            "Maharashtra",
            "Manipur",
            "Meghalaya",
            "Mizoram",
            "Nagaland",
            "Punjab",
            "Rajasthan",
            "Sikkim",
            "Tamil Nadu",
            "Telangana",
            "Tripura",
            "Uttarakhand",
            "Uttar Pradesh",
            "West Bengal"});
            this.textBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.textBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.textBox2.Location = new System.Drawing.Point(321, 163);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(170, 31);
            this.textBox2.TabIndex = 3;
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(321, 269);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(92, 29);
            this.button1.TabIndex = 4;
            this.button1.Text = "&Save";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(75, 29);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(606, 22);
            this.label3.TabIndex = 5;
            this.label3.Text = "Code To Perform Auto Complete TextBox With PopUp Menu In C#";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(219, 115);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(96, 22);
            this.label4.TabIndex = 6;
            this.label4.Text = "&Country:-";
            // 
            // textBox3
            // 
            this.textBox3.AutoCompleteCustomSource.AddRange(new string[] {
            "Adoni",
            "Amaravati",
            "Anantapur",
            "Chandragiri",
            "Chittoor",
            "Dowlaiswaram",
            "Eluru",
            "Guntur",
            "Kadapa",
            "Kakinada",
            "Kurnool",
            "Machilipatnam",
            "Nagarjunakoṇḍa",
            "Rajahmundry",
            "Srikakulam",
            "Tirupati",
            "Vijayawada",
            "Visakhapatnam",
            "Vizianagaram",
            "Yemmiganur",
            "Arunachal Pradesh",
            "Itanagar",
            "Assam",
            "Dhuburi",
            "Dibrugarh",
            "Dispur",
            "Guwahati",
            "Jorhat",
            "Nagaon",
            "Sivasagar",
            "Silchar",
            "Tezpur",
            "Tinsukia",
            "Bihar",
            "Ara",
            "Barauni",
            "Begusarai",
            "Bettiah",
            "Bhagalpur",
            "Bihar Sharif",
            "Bodh Gaya",
            "Buxar",
            "Chapra",
            "Darbhanga",
            "Dehri",
            "Dinapur Nizamat",
            "Gaya",
            "Hajipur",
            "Jamalpur",
            "Katihar",
            "Madhubani",
            "Motihari",
            "Munger",
            "Muzaffarpur",
            "Patna",
            "Purnia",
            "Pusa",
            "Saharsa",
            "Samastipur",
            "Sasaram",
            "Sitamarhi",
            "Siwan",
            "Chandigarh (union territory)",
            "Chandigarh",
            "Chhattisgarh",
            "Ambikapur",
            "Bhilai",
            "Bilaspur",
            "Dhamtari",
            "Durg",
            "Jagdalpur",
            "Raipur",
            "Rajnandgaon",
            "Dadra and Nagar Haveli and Daman and Diu (union territory)",
            "Daman",
            "Diu",
            "Silvassa",
            "Delhi (national capital territory)",
            "Delhi",
            "New Delhi",
            "Goa",
            "Madgaon",
            "Panaji",
            "Gujarat",
            "Ahmadabad",
            "Amreli",
            "Bharuch",
            "Bhavnagar",
            "Bhuj",
            "Dwarka",
            "Gandhinagar",
            "Godhra",
            "Jamnagar",
            "Junagadh",
            "Kandla",
            "Khambhat",
            "Kheda",
            "Mahesana",
            "Morbi",
            "Nadiad",
            "Navsari",
            "Okha",
            "Palanpur",
            "Patan",
            "Porbandar",
            "Rajkot",
            "Surat",
            "Surendranagar",
            "Valsad",
            "Veraval",
            "Haryana",
            "Ambala",
            "Bhiwani",
            "Chandigarh",
            "Faridabad",
            "Firozpur Jhirka",
            "Gurugram",
            "Hansi",
            "Hisar",
            "Jind",
            "Kaithal",
            "Karnal",
            "Kurukshetra",
            "Panipat",
            "Pehowa",
            "Rewari",
            "Rohtak",
            "Sirsa",
            "Sonipat",
            "Himachal Pradesh",
            "Bilaspur",
            "Chamba",
            "Dalhousie",
            "Dharmshala",
            "Hamirpur",
            "Kangra",
            "Kullu",
            "Mandi",
            "Nahan",
            "Shimla",
            "Una",
            "Jammu and Kashmir (union territory)",
            "Anantnag",
            "Baramula",
            "Doda",
            "Gulmarg",
            "Jammu",
            "Kathua",
            "Punch",
            "Rajouri",
            "Srinagar",
            "Udhampur",
            "Jharkhand",
            "Bokaro",
            "Chaibasa",
            "Deoghar",
            "Dhanbad",
            "Dumka",
            "Giridih",
            "Hazaribag",
            "Jamshedpur",
            "Jharia",
            "Rajmahal",
            "Ranchi",
            "Saraikela",
            "Karnataka",
            "Badami",
            "Ballari",
            "Bengaluru",
            "Belagavi",
            "Bhadravati",
            "Bidar",
            "Chikkamagaluru",
            "Chitradurga",
            "Davangere",
            "Halebid",
            "Hassan",
            "Hubballi-Dharwad",
            "Kalaburagi",
            "Kolar",
            "Madikeri",
            "Mandya",
            "Mangaluru",
            "Mysuru",
            "Raichur",
            "Shivamogga",
            "Shravanabelagola",
            "Shrirangapattana",
            "Tumakuru",
            "Vijayapura",
            "Kerala",
            "Alappuzha",
            "Vatakara",
            "Idukki",
            "Kannur",
            "Kochi",
            "Kollam",
            "Kottayam",
            "Kozhikode",
            "Mattancheri",
            "Palakkad",
            "Thalassery",
            "Thiruvananthapuram",
            "Thrissur",
            "Ladakh (union territory)",
            "Kargil",
            "Leh",
            "Madhya Pradesh",
            "Balaghat",
            "Barwani",
            "Betul",
            "Bharhut",
            "Bhind",
            "Bhojpur",
            "Bhopal",
            "Burhanpur",
            "Chhatarpur",
            "Chhindwara",
            "Damoh",
            "Datia",
            "Dewas",
            "Dhar",
            "Dr. Ambedkar Nagar (Mhow)",
            "Guna",
            "Gwalior",
            "Hoshangabad",
            "Indore",
            "Itarsi",
            "Jabalpur",
            "Jhabua",
            "Khajuraho",
            "Khandwa",
            "Khargone",
            "Maheshwar",
            "Mandla",
            "Mandsaur",
            "Morena",
            "Murwara",
            "Narsimhapur",
            "Narsinghgarh",
            "Narwar",
            "Neemuch",
            "Nowgong",
            "Orchha",
            "Panna",
            "Raisen",
            "Rajgarh",
            "Ratlam",
            "Rewa",
            "Sagar",
            "Sarangpur",
            "Satna",
            "Sehore",
            "Seoni",
            "Shahdol",
            "Shajapur",
            "Sheopur",
            "Shivpuri",
            "Ujjain",
            "Vidisha",
            "Maharashtra",
            "Ahmadnagar",
            "Akola",
            "Amravati",
            "Aurangabad",
            "Bhandara",
            "Bhusawal",
            "Bid",
            "Buldhana",
            "Chandrapur",
            "Daulatabad",
            "Dhule",
            "Jalgaon",
            "Kalyan",
            "Karli",
            "Kolhapur",
            "Mahabaleshwar",
            "Malegaon",
            "Matheran",
            "Mumbai",
            "Nagpur",
            "Nanded",
            "Nashik",
            "Osmanabad",
            "Pandharpur",
            "Parbhani",
            "Pune",
            "Ratnagiri",
            "Sangli",
            "Satara",
            "Sevagram",
            "Solapur",
            "Thane",
            "Ulhasnagar",
            "Vasai-Virar",
            "Wardha",
            "Yavatmal",
            "Manipur",
            "Imphal",
            "Meghalaya",
            "Cherrapunji",
            "Shillong",
            "Mizoram",
            "Aizawl",
            "Lunglei",
            "Nagaland",
            "Kohima",
            "Mon",
            "Phek",
            "Wokha",
            "Zunheboto",
            "Odisha",
            "Balangir",
            "Baleshwar",
            "Baripada",
            "Bhubaneshwar",
            "Brahmapur",
            "Cuttack",
            "Dhenkanal",
            "Kendujhar",
            "Konark",
            "Koraput",
            "Paradip",
            "Phulabani",
            "Puri",
            "Sambalpur",
            "Udayagiri",
            "Puducherry (union territory)",
            "Karaikal",
            "Mahe",
            "Puducherry",
            "Yanam",
            "Punjab",
            "Amritsar",
            "Batala",
            "Chandigarh",
            "Faridkot",
            "Firozpur",
            "Gurdaspur",
            "Hoshiarpur",
            "Jalandhar",
            "Kapurthala",
            "Ludhiana",
            "Nabha",
            "Patiala",
            "Rupnagar",
            "Sangrur",
            "Rajasthan",
            "Abu",
            "Ajmer",
            "Alwar",
            "Amer",
            "Barmer",
            "Beawar",
            "Bharatpur",
            "Bhilwara",
            "Bikaner",
            "Bundi",
            "Chittaurgarh",
            "Churu",
            "Dhaulpur",
            "Dungarpur",
            "Ganganagar",
            "Hanumangarh",
            "Jaipur",
            "Jaisalmer",
            "Jalor",
            "Jhalawar",
            "Jhunjhunu",
            "Jodhpur",
            "Kishangarh",
            "Kota",
            "Merta",
            "Nagaur",
            "Nathdwara",
            "Pali",
            "Phalodi",
            "Pushkar",
            "Sawai Madhopur",
            "Shahpura",
            "Sikar",
            "Sirohi",
            "Tonk",
            "Udaipur",
            "Sikkim",
            "Gangtok",
            "Gyalshing",
            "Lachung",
            "Mangan",
            "Tamil Nadu",
            "Arcot",
            "Chengalpattu",
            "Chennai",
            "Chidambaram",
            "Coimbatore",
            "Cuddalore",
            "Dharmapuri",
            "Dindigul",
            "Erode",
            "Kanchipuram",
            "Kanniyakumari",
            "Kodaikanal",
            "Kumbakonam",
            "Madurai",
            "Mamallapuram",
            "Nagappattinam",
            "Nagercoil",
            "Palayamkottai",
            "Pudukkottai",
            "Rajapalayam",
            "Ramanathapuram",
            "Salem",
            "Thanjavur",
            "Tiruchchirappalli",
            "Tirunelveli",
            "Tiruppur",
            "Thoothukudi",
            "Udhagamandalam",
            "Vellore",
            "Telangana",
            "Hyderabad",
            "Karimnagar",
            "Khammam",
            "Mahbubnagar",
            "Nizamabad",
            "Sangareddi",
            "Warangal",
            "Tripura",
            "Agartala",
            "Uttar Pradesh",
            "Agra",
            "Aligarh",
            "Amroha",
            "Ayodhya",
            "Azamgarh",
            "Bahraich",
            "Ballia",
            "Banda",
            "Bara Banki",
            "Bareilly",
            "Basti",
            "Bijnor",
            "Bithur",
            "Budaun",
            "Bulandshahr",
            "Deoria",
            "Etah",
            "Etawah",
            "Faizabad",
            "Farrukhabad-cum-Fatehgarh",
            "Fatehpur",
            "Fatehpur Sikri",
            "Ghaziabad",
            "Ghazipur",
            "Gonda",
            "Gorakhpur",
            "Hamirpur",
            "Hardoi",
            "Hathras",
            "Jalaun",
            "Jaunpur",
            "Jhansi",
            "Kannauj",
            "Kanpur",
            "Lakhimpur",
            "Lalitpur",
            "Lucknow",
            "Mainpuri",
            "Mathura",
            "Meerut",
            "Mirzapur-Vindhyachal",
            "Moradabad",
            "Muzaffarnagar",
            "Partapgarh",
            "Pilibhit",
            "Prayagraj",
            "Rae Bareli",
            "Rampur",
            "Saharanpur",
            "Sambhal",
            "Shahjahanpur",
            "Sitapur",
            "Sultanpur",
            "Tehri",
            "Varanasi",
            "Uttarakhand",
            "Almora",
            "Dehra Dun",
            "Haridwar",
            "Mussoorie",
            "Nainital",
            "Pithoragarh",
            "West Bengal",
            "Alipore",
            "Alipur Duar",
            "Asansol",
            "Baharampur",
            "Bally",
            "Balurghat",
            "Bankura",
            "Baranagar",
            "Barasat",
            "Barrackpore",
            "Basirhat",
            "Bhatpara",
            "Bishnupur",
            "Budge Budge",
            "Burdwan",
            "Chandernagore",
            "Darjeeling",
            "Diamond Harbour",
            "Dum Dum",
            "Durgapur",
            "Halisahar",
            "Haora",
            "Hugli",
            "Ingraj Bazar",
            "Jalpaiguri",
            "Kalimpong",
            "Kamarhati",
            "Kanchrapara",
            "Kharagpur",
            "Cooch Behar",
            "Kolkata",
            "Krishnanagar",
            "Malda",
            "Midnapore",
            "Murshidabad",
            "Nabadwip",
            "Palashi",
            "Panihati",
            "Purulia",
            "Raiganj",
            "Santipur",
            "Shantiniketan",
            "Shrirampur",
            "Siliguri",
            "Siuri",
            "Tamluk",
            "Titagarh"});
            this.textBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.textBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.textBox3.Location = new System.Drawing.Point(321, 212);
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new System.Drawing.Size(170, 31);
            this.textBox3.TabIndex = 7;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(11F, 22F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(755, 499);
            this.Controls.Add(this.textBox3);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.textBox2);
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Margin = new System.Windows.Forms.Padding(6, 5, 6, 5);
            this.Name = "Form1";
            this.Text = "Form1";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox textBox3;

    }
}

